# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

commands:
  # https://github.com/volta-cli/website/issues/43#issuecomment-545393256
  setup-node:
    description: Install volta & ensure consistent node & yarn versions are installed
    steps:
      - run:
          name: Install volta
          command: |
            curl https://get.volta.sh | bash
            echo 'export VOLTA_HOME=$HOME/.volta' >> $BASH_ENV
            echo 'export PATH=$VOLTA_HOME/bin:$PATH' >> $BASH_ENV
      # export VOLTA_HOME=$HOME/.volta
      # export PATH=$VOLTA_HOME:$PATH
      # - run:
      #     name: Install node
      #     command: volta install node

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable
    shell: bash
    steps:
      - checkout
      - setup-node
      - run:
          name: 'Print Environment Info'
          command: printenv
      - run:
          name: 'Volta install'
          command: volta install node
      - run:
          name: 'Install npm dependencies'
          command: 'npm ci'
      # - run:
      #     name: 'Print Environment Info'
      #     command: 'npx lerna info'
      - run:
          name: 'Build Packages'
          command: 'npx lerna run build'

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build
